language: cpp

matrix:
  include:
    # Test Ubuntu 14.04 + gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
        - git clone https://github.com/glfw/glfw
        - cd glfw && mkdir build && cd build && cmake .. && make install
      script:
        - sh scripts/travis_build.sh
    # Test Docker based on Ubuntu 14.04 LTS + gcc
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh scripts/travis_build_docker.sh
    # Test Docker based on Ubuntu 16.04 LTS + gcc
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh scripts/travis_build_docker.sh scripts/Dockerfile.xenial xenial
    # Test Docker based on Ubuntu 18.04 LTS + gcc
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh scripts/travis_build_docker.sh scripts/Dockerfile.bionic bionic
    # Test Docker based on Ubuntu 18.04 LTS + gcc-latest
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh scripts/travis_build_docker.sh scripts/Dockerfile.bionic.gcc-latest bionic-gcc-latest
    # Test Docker based on Ubuntu 18.04 LTS + clang-latest
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh scripts/travis_build_docker.sh scripts/Dockerfile.bionic.gcc-latest bionic-clang-latest
    # Test OS X 10.11 + Xcode 7.3 + clang
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      before_install:
        - brew update
        - brew install glfw
      script:
        - sh scripts/travis_build.sh
    # Test OS X 10.12 + Xcode 8.3 + clang
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      before_install:
        - brew update
        - brew install glfw
      script:
        - sh scripts/travis_build.sh
    # Test OS X 10.12 + Xcode 9 + clang
    - os: osx
      osx_image: xcode9
      compiler: clang
      before_install:
        - brew update
        - brew install glfw
      script:
        - sh scripts/travis_build.sh
